# Version format
version: 0.1.{build}

branches:
  only:
  - sqlserver

# Operating system 
os: Windows Server 2012 R2
# Custom clone folder (variables are not expanded here).
clone_folder: c:\gopath\src\github.com\omniscale\imposm3

# Environment variables
environment:
  GOROOT: c:\go
  GOPATH: c:\gopath
  PROJ:   github.com\omniscale\imposm3

services:
  - postgresql94
  - mssql2014

# Scripts that run after cloning repository
install:
  - mkdir c:\projects
  - mkdir c:\projects\deps\include c:\projects\deps\lib c:\projects\deps\bin
  - set PATH=%GOROOT%\bin;%PATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - set PATH=c:\projects\deps\bin;c:\projects\osmosis\bin;C:\Program Files\PostgreSQL\9.4\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  #- set GOPATH=%GOPATH%\src\%PROJ%\Godeps\_workspace;%GOPATH%
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --needed -S autoconf perl automake libtool make mingw-w64-x86_64-geos protobuf" 
  - set MSYSTEM=MINGW64
  - go version
  - go env 
  #go dependencies
  #- go get github.com/golang/protobuf/proto                  
  #- go get github.com/golang/protobuf/protoc-gen-go
  - go get github.com/tools/godep
  # geos
  - C:\msys64\usr\bin\bash -lc "geos-config --version"
  # osmosis
  - ps: (New-Object Net.WebClient).DownloadFile('http://bretth.dev.openstreetmap.org/osmosis-build/osmosis-latest.zip', 'C:\projects\osmosis-latest.zip')
  - 7z x -y C:\projects\osmosis-latest.zip -oC:\projects\osmosis > nul
  # protoc
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/google/protobuf/releases/download/v2.6.1/protoc-2.6.1-win32.zip', 'C:\projects\protoc.zip')
  - 7z x -y C:\projects\protoc.zip -oC:\projects\deps\bin > nul
  # LevelDB
  - git clone https://github.com/zalanyib/leveldb-mingw.git c:\projects\leveldb  

  #python dependencies 
  #- git clone https://github.com/Alexpux/MINGW-packages c:\msys64\repos
  #- C:\msys64\usr\bin\bash -lc "cd /c/msys64/repos/mingw-w64-python-pip; PATH=$PATH:/mingw64/bin; exec 0</dev/null; ln -s /mingw64/bin/libgeos_c.dll /mingw64/bin/geos.dll; makepkg-mingw -s --noconfirm --noprogressbar --skippgpcheck --pkg mingw-w64-x86_64-python2-pip; pacman --noprogressbar --noconfirm -U mingw-w64-x86_64-python2-pip*.pkg.tar.xz; pip install nose shapely psycopg2"
  #- ln -s /mingw64/bin/libgeos_c.dll /mingw64/bin/geos.dll
  #- copy C:\msys64\mingw64\bin\libgeos_c.dll C:\msys64\mingw64\bin\geos.dll
  #- cd c:\msys64\repos\mingw-w64-python-pip
  #- makepkg-mingw -sL --noconfirm --noprogressbar --skippgpcheck --pkg mingw-w64-x86_64-python2-pip
  #- pacman --noconfirm -U mingw-w64-python-pip*.pkg.tar.xz
  #- SET PATH=C:\python27-x64;;%PATH%
  - ps: Start-FileDownload "http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe"
  - osgeo4w-setup-x86_64.exe --root C:\projects\osgeo4w --packages "geos,python-shapely,python-core,psycopg2" -N -d -n -a -q --site "http://download.osgeo.org/osgeo4w/"
  - SET PATH=C:\projects\osgeo4w\apps\Python27\Scripts;C:\projects\osgeo4w\bin;%PATH%
  - SET PYTHONHOME=C:\projects\osgeo4w\apps\Python27
  - python --version
  - ps: Start-FileDownload https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip --version
  - pip install nose python-tds

# To run your custom scripts instead of automatic MSBuild
build_script:
  # Build leveldb  
  - appveyor AddCompilationMessage "Building leveldb"
  - cd c:\projects\leveldb 
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/leveldb; PATH=$PATH:/mingw64/bin; exec 0</dev/null; make"
  - xcopy .\include\leveldb c:\projects\deps\include\leveldb\ /E
  - copy leveldb.dll c:\projects\deps\bin
  - copy leveldb.lib c:\projects\deps\lib 
  # Build Imposm3
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor AddCompilationMessage "Building Imposm3"
  - set CGO_CFLAGS=-I c:\projects\deps\include
  - set CGO_LDFLAGS=-L c:\projects\deps\lib
  - C:\msys64\usr\bin\bash -lc "cd /c/gopath/src/github.com/omniscale/imposm3; PATH=$PATH:/mingw64/bin; exec 0</dev/null; make build"
  - appveyor AddCompilationMessage "Build successful" 

before_test:
  # setup the PostgreSQL database
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - createuser --no-superuser --no-createrole --createdb osm
  - createdb -E UTF8 -O osm osm
  - psql -d osm -c "CREATE EXTENSION postgis;"
  - psql -d osm -c "CREATE EXTENSION hstore;" # only required for hstore support
  - echo ALTER USER osm WITH PASSWORD 'osm'; |psql -d osm
  - SET PGUSER=osm
  - SET PGPASSWORD=osm
  - SET PGDATABASE=osm
  # setup mssql
  - ps: >-
      # Source: http://geekswithblogs.net/TedStatham/archive/2014/06/13/setting-the-ports-for-a-named-sql-server-instance-using.aspx
      # Set the $instanceName value below to the name of the instance you
      # want to configure a static port for. This could conceivably be
      # passed into the script as a parameter.

      [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Smo") | Out-Null
      [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement") | Out-Null

      $instanceName = 'SQL2014'
      $computerName = $env:COMPUTERNAME
      $smo = 'Microsoft.SqlServer.Management.Smo.'
      $wmi = New-Object ($smo + 'Wmi.ManagedComputer')

      # For the named instance, on the current computer, for the TCP protocol,
      # loop through all the IPs and configure them to use the standard port
      # of 1433.

      $uri = "ManagedComputer[@Name='$computerName']/ServerInstance[@Name='$instanceName']/ServerProtocol[@Name='Tcp']"
      $Tcp = $wmi.GetSmoObject($uri)

      foreach ($ipAddress in $Tcp.IPAddresses)
      {
          $ipAddress.IPAddressProperties["TcpDynamicPorts"].Value = ""
          $ipAddress.IPAddressProperties["TcpPort"].Value = "1433"
      }

      $Tcp.Alter()

      # Restart the named instance of SQL Server to enable the changes.
      Restart-Service "MSSQL`$$instanceName"

  #- $sqlInstance = "(local)\SQL2014"
  - sqlcmd -S "localhost" -Q "Use [master]; CREATE DATABASE osm; CREATE LOGIN [osm] WITH PASSWORD=N'osm', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF; CREATE USER [osm] FOR LOGIN [osm]; ALTER ROLE [db_datareader] ADD MEMBER [osm]; ALTER ROLE [db_datawriter] ADD MEMBER [osm];

  # XXX copy dlls in imposm path
  - copy C:\projects\deps\bin\leveldb.dll C:\gopath\src\github.com\omniscale\imposm3
  - copy C:\msys64\mingw64\bin\libgeos.dll C:\gopath\src\github.com\omniscale\imposm3
  - copy C:\msys64\mingw64\bin\libgeos_c.dll C:\gopath\src\github.com\omniscale\imposm3
  - copy "C:\msys64\mingw64\bin\libstdc++-6.dll" C:\gopath\src\github.com\omniscale\imposm3
  - copy C:\msys64\mingw64\bin\libwinpthread-1.dll C:\gopath\src\github.com\omniscale\imposm3
  - copy C:\msys64\mingw64\bin\libgcc_s_seh-1.dll C:\gopath\src\github.com\omniscale\imposm3

# To run your custom scripts instead of automatic tests
test_script:
  # Unit tests
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Add-AppveyorTest "Unit Tests" -Outcome Running
  - C:\msys64\usr\bin\bash -lc "cd /c/gopath/src/github.com/omniscale/imposm3; PATH=$PATH:/mingw64/bin; exec 0</dev/null; make test-unit"
  #- make test-unit 
  - ps: Update-AppveyorTest "Unit Tests" -Outcome Passed
  # System tests 
  - ps: Add-AppveyorTest "System tests" -Outcome Running 
  #- C:\msys64\usr\bin\bash -lc "cd /c/gopath/src/github.com/omniscale/imposm3; PATH=$PATH:/mingw64/bin; exec 0</dev/null; make test-system" 
  #- SET PATH=C:\msys64\usr\bin;%PATH%
  - make test-system 
  - ps: Update-AppveyorTest "System tests" -Outcome Passed

# on successful build
on_success:
  - mkdir C:\projects\imposm3
  - copy C:\gopath\src\github.com\omniscale\imposm3\imposm3.exe c:\projects\imposm3
  - copy C:\projects\deps\bin\leveldb.dll c:\projects\imposm3
  - copy C:\msys64\mingw64\bin\libgeos.dll c:\projects\imposm3
  - copy C:\msys64\mingw64\bin\libgeos_c.dll c:\projects\imposm3
  - copy "C:\msys64\mingw64\bin\libstdc++-6.dll" c:\projects\imposm3
  - copy C:\msys64\mingw64\bin\libwinpthread-1.dll c:\projects\imposm3
  - copy C:\msys64\mingw64\bin\libgcc_s_seh-1.dll c:\projects\imposm3
  - 7z a C:\projects\imposm3.zip c:\projects\imposm3
  - ps: Push-AppveyorArtifact C:\projects\imposm3.zip -FileName imposm3-$($env:APPVEYOR_REPO_BRANCH)-$((Get-Date).ToUniversalTime().ToString("yyyyMMdd"))-$(($env:APPVEYOR_REPO_COMMIT).Substring(0, 7))-win-x86-64.zip
